name: Deploy GitHub Pages

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Sync sources
        run: |
          chmod +x scripts/sync_book.sh
          bash scripts/sync_book.sh

      - name: Install cargo packages
        run: cargo install mdbook-alerts

      - name: Build site with mdbook
        run: mdbook build
        working-directory: ./book

      - name: Generate sitemap
        run: |
          npx sscli --no-clean -c '**,monthly' -f xml --base https://nh4ttruong.github.io/portswigger
        working-directory: ./book/html

      - name: Custom git_repository_edit_url
        run: |
          find ./book/html -name "*.html" -exec sed -i 's|edit/main/src|edit/main|g' {} +

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          publish_branch: gh-pages
        
      - name: Deploy to GitHub Pages (Dev)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/feature/mdbook'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          publish_branch: gh-pages-dev
